In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/FakeNewsNet.csv")

In [ ]:
df.head()

title  \
0  Kandi Burruss Explodes Over Rape Accusation on...   
1  People's Choice Awards 2018: The best red carp...   
2  Sophia Bush Sends Sweet Birthday Message to 'O...   
3  Colombian singer Maluma sparks rumours of inap...   
4  Gossip Girl 10 Years Later: How Upper East Sid...   

                                            news_url        source_domain  \
0  http://toofab.com/2017/05/08/real-housewives-a...           toofab.com   
1  https://www.today.com/style/see-people-s-choic...        www.today.com   
2  https://www.etonline.com/news/220806_sophia_bu...     www.etonline.com   
3  https://www.dailymail.co.uk/news/article-33655...  www.dailymail.co.uk   
4  https://www.zerchoo.com/entertainment/gossip-g...      www.zerchoo.com   

   tweet_num  real  
0         42     1  
1          0     1  
2         63     1  
3         20     1  
4         38     1

In [ ]:
import pandas as pd  # Make sure pandas is imported

# Check if 'isnull' is defined as something else
print(type(pd.isnull))  # Should print <class 'function'>

# If it's not a function, reset it
pd.isnull = pd.DataFrame.isnull

# Now try again
df.isnull().sum()

<class 'function'>


title              0
news_url         330
source_domain    330
tweet_num          0
real               0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

title            0
news_url         0
source_domain    0
tweet_num        0
real             0
dtype: int64

In [ ]:
x=df.drop('real',axis=1)

In [ ]:
y=df["real"]

In [ ]:
x.shape
y.shape

(22866,)

In [ ]:
import tensorflow as tf


In [ ]:
tf.__version__

'2.15.0'

In [ ]:
from tensorflow.keras import layers
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
voc_size=5000

In [ ]:
msg=x.copy()

In [ ]:
msg["title"]

0        Kandi Burruss Explodes Over Rape Accusation on...
1        People's Choice Awards 2018: The best red carp...
2        Sophia Bush Sends Sweet Birthday Message to 'O...
3        Colombian singer Maluma sparks rumours of inap...
4        Gossip Girl 10 Years Later: How Upper East Sid...
                               ...                        
23191    Pippa Middleton wedding: In case you missed it...
23192    Zayn Malik & Gigi Hadid’s Shocking Split: Why ...
23193    Jessica Chastain Recalls the Moment Her Mother...
23194    Tristan Thompson Feels "Dumped" After Khloé Ka...
23195    Kelly Clarkson Performs a Medley of Kendrick L...
Name: title, Length: 22866, dtype: object

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.stem.porter import PorterStemmer
p=PorterStemmer()
corpus=[]
for title in msg["title"]:
  review=re.sub("[^a-zA-Z]","  ",title)
  review=review.lower()
  review=review.split()
  review=[p.stem(word) for word in review if not word in stopwords.words("english")]
  review=" ".join(review)
  corpus.append(review)


In [ ]:
corpus

['kandi burruss explod rape accus real housew atlanta reunion video',
 'peopl choic award best red carpet look',
 'sophia bush send sweet birthday messag one tree hill co star hilari burton breyton eva',
 'colombian singer maluma spark rumour inappropri relationship aunt',
 'gossip girl year later upper east sider shock world chang pop cultur forev',
 'gwen stefani got dump blake shelton jealousi drama exclus',
 'broward counti sheriff fire lie parkland',
 'amber rose shut french montana date rumor call rapper bruvaaa',
 'mindi kale make first post babi appear disneyland wrinkl time co star',
 'katharin mcphee butcher toni nomin drink',
 'wag miami star ashley nicol robert philip wheeler marri',
 'mel gibson hollywood pedophil nowher left hide',
 'medium tyler henri address chill messag kristin cavallari deceas brother express read',
 'dwt season result week disney night',
 'reason tarek el moussa overcom latest back injuri',
 'david cassidi cut estrang daughter kati complet leav son b

In [ ]:
onerepr=[one_hot(words,voc_size) for words in corpus]

In [ ]:
onerepr

[[1035, 1449, 249, 1450, 1024, 1451, 1243, 1937, 2575, 3438],
 [3127, 4335, 1906, 3961, 2580, 3994, 3112],
 [4701,
  2439,
  4317,
  3442,
  1412,
  829,
  2773,
  3260,
  29,
  2105,
  1237,
  4119,
  530,
  4533,
  1099],
 [1466, 4641, 3053, 1795, 2620, 1384, 1395, 4673],
 [3197, 2841, 3541, 453, 4492, 157, 1049, 3008, 3666, 4815, 3661, 3392, 4042],
 [1835, 2928, 327, 4254, 2848, 843, 185, 3314, 33],
 [3202, 1903, 3372, 1693, 4230, 2711],
 [2146, 1505, 3500, 3286, 2717, 2017, 809, 1671, 3625, 4339],
 [2314, 539, 952, 3227, 3518, 3057, 1779, 3056, 2529, 4964, 2105, 1237],
 [4397, 3486, 3316, 4409, 4602, 1721],
 [3688, 4947, 1237, 666, 3513, 3020, 1585, 4351, 276],
 [1935, 971, 4606, 2865, 3502, 2931, 4318],
 [4094, 2926, 1035, 245, 3524, 829, 207, 3935, 1920, 4415, 907, 3691],
 [4870, 4913, 1665, 1550, 1323, 2656],
 [227, 2895, 2416, 4927, 914, 819, 1682, 2218],
 [2100, 3672, 3259, 3879, 4026, 8, 3027, 2036, 3751, 1381],
 [3859, 3416, 1744, 3240, 71, 2147, 2341],
 [3265, 3179, 1905, 1

In [ ]:
sent_len=20
embedded_docs=pad_sequences(onerepr,padding="pre",maxlen=sent_len)
embedded_docs

array([[   0,    0,    0, ..., 1937, 2575, 3438],
       [   0,    0,    0, ..., 2580, 3994, 3112],
       [   0,    0,    0, ...,  530, 4533, 1099],
       ...,
       [   0,    0,    0, ..., 1035, 2739, 4094],
       [   0,    0,    0, ..., 4570, 1504,   33],
       [   0,    0,    0, ..., 4543, 1259, 1906]], dtype=int32)

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1035,
       1449,  249, 1450, 1024, 1451, 1243, 1937, 2575, 3438], dtype=int32)

In [ ]:
model=Sequential()
embedding_vector_features=40
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_len))
model.add(LSTM(100))
model.add(Dense(1,activation="sigmoid"))
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])
print(model.summary())


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
import numpy as np
x_f=np.array(embedded_docs)
y_f=np.array(y)

In [ ]:
x_f.shape

(22866, 20)

In [ ]:
y_f.shape

(22866,)

In [ ]:
from tensorflow.keras.layers import Dropout
model=Sequential()
embedding_vector_features=40
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_len))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dense(1,activation="sigmoid"))
model.add(Dropout(0.3))
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])
print(model.summary())


Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 20, 40)            0         
                                                                 
 lstm_2 (LSTM)               (None, 100)               56400     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
 dropout_1 (Dropout)         (None, 1)                 0         
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_f,y_f,test_size=0.33,random_state=42)

In [ ]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10)

Epoch 1/10
479/479 [==============================] - 16s 28ms/step - loss: 3.8204 - accuracy: 0.6310 - val_loss: 0.6641 - val_accuracy: 0.6072
Epoch 2/10
479/479 [==============================] - 13s 28ms/step - loss: 3.8056 - accuracy: 0.6561 - val_loss: 0.5314 - val_accuracy: 0.7974
Epoch 3/10
479/479 [==============================] - 13s 27ms/step - loss: 3.8095 - accuracy: 0.6634 - val_loss: 0.5359 - val_accuracy: 0.8039
Epoch 4/10
479/479 [==============================] - 12s 26ms/step - loss: 3.6610 - accuracy: 0.6768 - val_loss: 0.5654 - val_accuracy: 0.7915
Epoch 5/10
479/479 [==============================] - 12s 25ms/step - loss: 3.7572 - accuracy: 0.6791 - val_loss: 0.5602 - val_accuracy: 0.7684
Epoch 6/10
479/479 [==============================] - 14s 29ms/step - loss: 3.8169 - accuracy: 0.6780 - val_loss: 0.5309 - val_accuracy: 0.8061
Epoch 7/10
479/479 [==============================] - 14s 29ms/step - loss: 3.7019 - accuracy: 0.6901 - val_loss: 0.5362 - val_accuracy:

In [ ]:
y_pred=model.predict(x_test)

236/236 [==============================] - 2s 7ms/step


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [ ]:
confusion_matrix(y_test,y_pred.round())

array([[1235,  607],
       [ 935, 4769]])

In [ ]:
accuracy_score(y_test,y_pred.round())

0.7956533262655712

In [ ]:
classification_report(y_test,y_pred.round())

'              precision    recall  f1-score   support\n\n           0       0.57      0.67      0.62      1842\n           1       0.89      0.84      0.86      5704\n\n    accuracy                           0.80      7546\n   macro avg       0.73      0.75      0.74      7546\nweighted avg       0.81      0.80      0.80      7546\n'

In [ ]:
# prompt: i want add input from the user

def predict_user_input(user_input):
  review = re.sub("[^a-zA-Z]", "  ", user_input)
  review = review.lower()
  review = review.split()
  review = [p.stem(word) for word in review if not word in stopwords.words("english")]
  review = " ".join(review)
  one_hot_rep = one_hot(review, voc_size)
  embedded_doc = pad_sequences([one_hot_rep], padding="pre", maxlen=sent_len)
  prediction = model.predict(embedded_doc)
  return prediction

user_input = input("Enter a news title: ")
prediction = predict_user_input(user_input)

if prediction[0][0] >= 0.5:
  print("The news is likely real.")
else:
  print("The news is likely fake.")
